### ISSUE TITLE
Error when launching scan "KeyError: 'title'

### ISSUE THREAD

**Issue by ValhalaSCorp** [Ostorlab/ostorlab#572]
**Describe the bug**

I'm trying to run my first scan with this command: ostorlab scan run --agent agent/ostorlab/tsunami  ip 192.168.0.1/24 after install tsunami agent.

**Expected behavior**
Scan running without issues.

**Desktop (please complete the following information):**
 - OS: Kali Linux

**Additional context**
This is the return I receive

🔺 ERROR: Error while initializing swarm.
Traceback (most recent call last):
  File "/home/valhalascorp/.local/bin/ostorlab", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/valhalascorp/.local/lib/python3.11/site-packages/ostorlab/__init__.py", line 27, in main
    rootcli(None)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/valhalascorp/.local/lib/python3.11/site-packages/ostorlab/cli/scan/run/assets/ip.py", line 48, in ip_cli
    title=ctx.obj["title"],
          ~~~~~~~^^^^^^^^^
KeyError: 'title'

**Comment by 3asm** [comment]
Thanks, @ValhalaSCorp for reporting the issue. I managed to identify the root cause and deploy a fix.

The issue is due to non-graceful handling of errors when the runtime can't init Docker Swarm.

You should have a clearer error message, however, in your case, you still need to address the issue with making Docker Swarm is working in your env.

**Comment by ValhalaSCorp** [comment]
> Thanks, @ValhalaSCorp for reporting the issue. I managed to identify the root cause and deploy a fix.
> 
> The issue is due to non-graceful handling of errors when the runtime can't init Docker Swarm.
> 
> You should have a clearer error message, however, in your case, you still need to address the issue with making Docker Swarm is working in your env.


Hello

I restarted Docker Swarm and the problem was resolved.

Thanks!

**Comment by 3asm** [comment]
Awesome. Thanks for the feedback.
